name: Docker CI

on:
  push:
    branches: [ "main", "devops" ]
  pull_request:

jobs:
  docker-build-and-smoke-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Docker image
        run: |
          docker build -t mentor-match ./backend

      - name: Run container
        run: docker run -d --name mentor-match -p 3000:3000 -e PORT=3000 mentor-match


      - name: Wait for server to start
        run: sleep 10

      - name: Smoke test (HTTP on /)
        run: |
          curl -f http://localhost:3000/

      - name: Show container logs (always)
        if: always()
        run: docker logs mentor-match

